# Generated by Django 3.1.7 on 2021-04-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210405_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='content',
            new_name='post',
        ),
    ]
