# Generated by Django 3.1.7 on 2021-04-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210405_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
