# Generated by Django 3.1.7 on 2021-04-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210405_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='likes_by',
            new_name='liked_by',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='like',
        ),
    ]
