# Generated by Django 3.1.7 on 2021-04-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210405_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-created_at']},
        ),
    ]
