# Generated by Django 3.1.7 on 2021-04-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210319_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_used',
            new_name='is_private',
        ),
    ]
