# Generated by Django 3.1.7 on 2021-04-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210401_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_private',
            new_name='is_used',
        ),
    ]
