# Generated by Django 3.1.7 on 2021-04-01 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0002_auto_20210401_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='uid',
            new_name='user_uid',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='is_private',
        ),
        migrations.AddField(
            model_name='follower',
            name='is_private',
            field=models.ManyToManyField(default=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
