# Generated by Django 3.1.7 on 2021-04-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_auto_20210401_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='is_private',
        ),
        migrations.AddField(
            model_name='follower',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='authentication.User'),
        ),
    ]
