# Generated by Django 3.1.7 on 2021-04-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_auto_20210401_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user_uid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='following_to',
            new_name='user_to_follow',
        ),
        migrations.AlterField(
            model_name='follower',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
