# Generated by Django 3.1.7 on 2021-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0006_auto_20210401_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='authentication.User'),
        ),
    ]
