# Generated by Django 3.1.7 on 2021-04-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0007_auto_20210401_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='is_private',
        ),
    ]
