# Generated by Django 3.1.7 on 2021-04-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0009_follower_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='is_private',
        ),
    ]
